In [1]:
#import libraries
import pandas as pd
import numpy as np
import sys

In [2]:
#import data
data = pd.read_csv('random.csv',header=None)
#random = pd.read_csv('random.csv',header=None)

threshold = 0.0001
learningrate = 0.0001

In [40]:
data =pd.read_excel("Book1.xlsx")
threshold = 0.00001
learningrate = 0.0001

In [41]:
#split data into attributes and labels
inputs = data.iloc[:,:-1]
inputs.insert(0, 'bias', 1)
output=data.iloc[:,-1]

In [42]:
output

0    1
1    1
2   -1
3    1
4    1
5   -1
6   -1
7   -1
Name: Unnamed: 3, dtype: int64

In [43]:
result =[]
w = np.zeros(inputs.shape[1])
w[0] =0.3
SSE=10
SSEold=200000
changeinSSE=1
while changeinSSE>threshold:
#for i in range(10):
    prediction = np.dot(w.T,np.array(inputs).T)
    error = np.subtract(np.array(output),prediction)
    gradient = np.dot(error,np.array(inputs))
    SSE = np.sum(np.square(error)) ##SSEnew
    changeinSSE = SSEold-SSE
    result.append(np.append(w,SSE))
    w = w+learningrate*gradient.T
    SSEold=SSE


In [44]:
pd.DataFrame(result)

0         1             2         3         4
0     0.300000  0.000000  0.000000e+00  0.000000  8.720000
1     0.299760  0.000400  0.000000e+00 -0.000400  8.712451
2     0.299520  0.000800  0.000000e+00 -0.000800  8.704914
3     0.299281  0.001199 -4.440892e-20 -0.001199  8.697389
4     0.299041  0.001598 -4.440892e-20 -0.001598  8.689876
5     0.298802  0.001997 -4.440892e-20 -0.001997  8.682376
6     0.298563  0.002395 -4.440892e-20 -0.002395  8.674887
7     0.298324  0.002793 -4.440892e-20 -0.002793  8.667410
8     0.298085  0.003191 -4.440892e-20 -0.003191  8.659945
9     0.297847  0.003589 -4.440892e-20 -0.003589  8.652492
10    0.297609  0.003986 -4.440892e-20 -0.003986  8.645051
11    0.297371  0.004382 -8.881784e-20 -0.004382  8.637622
12    0.297133  0.004779 -8.881784e-20 -0.004779  8.630205
13    0.296895  0.005175 -8.881784e-20 -0.005175  8.622800
14    0.296657  0.005571 -8.881784e-20 -0.005571  8.615406
15    0.296420  0.005967 -4.440892e-20 -0.005967  8.608024
16    0.296183  0.006362  0.000000e+00 -0.006362  8.600654
17    0.295946  0.006757  0.000000e+00 -0.006757  8.593296
18    0.295709  0.007151  4.440892e-20 -0.007151  8.585950
19    0.295473  0.007546  4.440892e-20 -0.007546  8.578615
20    0.295236  0.007939  4.440892e-20 -0.007939  8.571293
21    0.295000  0.008333  4.440892e-20 -0.008333  8.563981
22    0.294764  0.008726  4.440892e-20 -0.008726  8.556682
23    0.294528  0.009119  4.440892e-20 -0.009119  8.549394
24    0.294293  0.009512  8.881784e-20 -0.009512  8.542118
25    0.294057  0.009905  8.881784e-20 -0.009905  8.534854
26    0.293822  0.010297  8.881784e-20 -0.010297  8.527601
27    0.293587  0.010688  8.881784e-20 -0.010688  8.520359
28    0.293352  0.011080  8.881784e-20 -0.011080  8.513130
29    0.293117  0.011471  4.440892e-20 -0.011471  8.505912
...        ...       ...           ...       ...       ...
4112  0.011166  0.481390  1.083336e-34 -0.481390  4.006539
4113  0.011157  0.481405  1.083336e-34 -0.481405  4.006528
4114  0.011148  0.481420  1.083336e-34 -0.481420  4.006518
4115  0.011139  0.481435  1.083336e-34 -0.481435  4.006507
4116  0.011130  0.481450  1.083336e-34 -0.481450  4.006497
4117  0.011121  0.481464  1.083336e-34 -0.481464  4.006487
4118  0.011112  0.481479  4.440892e-20 -0.481479  4.006476
4119  0.011104  0.481494  4.440892e-20 -0.481494  4.006466
4120  0.011095  0.481509  4.440892e-20 -0.481509  4.006455
4121  0.011086  0.481524  4.440892e-20 -0.481524  4.006445
4122  0.011077  0.481538  4.440892e-20 -0.481538  4.006435
4123  0.011068  0.481553  4.440892e-20 -0.481553  4.006425
4124  0.011059  0.481568  4.440892e-20 -0.481568  4.006414
4125  0.011050  0.481583  4.440892e-20 -0.481583  4.006404
4126  0.011042  0.481597  4.440892e-20 -0.481597  4.006394
4127  0.011033  0.481612  4.440892e-20 -0.481612  4.006384
4128  0.011024  0.481627  4.440892e-20 -0.481627  4.006373
4129  0.011015  0.481642  4.440892e-20 -0.481642  4.006363
4130  0.011006  0.481656  4.440892e-20 -0.481656  4.006353
4131  0.010997  0.481671  1.083336e-34 -0.481671  4.006343
4132  0.010989  0.481686 -4.440892e-20 -0.481686  4.006333
4133  0.010980  0.481700 -4.440892e-20 -0.481700  4.006323
4134  0.010971  0.481715 -4.440892e-20 -0.481715  4.006312
4135  0.010962  0.481730 -4.440892e-20 -0.481730  4.006302
4136  0.010953  0.481744 -4.440892e-20 -0.481744  4.006292
4137  0.010945  0.481759 -4.440892e-20 -0.481759  4.006282
4138  0.010936  0.481773 -4.440892e-20 -0.481773  4.006272
4139  0.010927  0.481788 -4.440892e-20 -0.481788  4.006262
4140  0.010918  0.481803 -4.440892e-20 -0.481803  4.006252
4141  0.010910  0.481817 -8.881784e-20 -0.481817  4.006242

[4142 rows x 5 columns]

In [52]:
# Imports
import numpy as np 
      
# Each row is a training example, each column is a feature  [X1, X2, X3]
X=np.array(([1,-1,1],[1,-1,-1],[-1,1,1],[-1,1,-1],[1,1,-1],[-1,-1,1],[1,1,1],[-1,-1,-1]), dtype=float)
y=np.array(([1],[1],[-1],[1],[1],[-1],[-1],[-1]), dtype=float)

# Define useful functions    

# Activation function
def sigmoid(t):
    return 1/(1+np.exp(-t))

# Derivative of sigmoid
def sigmoid_derivative(p):
    return p * (1 - p)

# Class definition
class NeuralNetwork:
    def __init__(self, x,y):
        self.input = x
        self.weights1= np.random.rand(self.input.shape[1],4) # considering we have 4 nodes in the hidden layer
        self.weights2 = np.random.rand(4,1)
        self.y = y
        self.output = np. zeros(y.shape)
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        return self.layer2
        
    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, 2*(self.y -self.output)*sigmoid_derivative(self.output))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y -self.output)*sigmoid_derivative(self.output), self.weights2.T)*sigmoid_derivative(self.layer1))
    
        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self, X, y):
        self.output = self.feedforward()
        self.backprop()
        

NN = NeuralNetwork(X,y)
for i in range(1500): # trains the NN 1,000 times
    if i % 100 ==0: 
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(NN.feedforward()))
        print ("Loss: \n" + str(np.mean(np.square(y - NN.feedforward())))) # mean sum squared loss
        print ("\n")
  
    NN.train(X, y)

for iteration # 0

Input : 
[[ 1. -1.  1.]
 [ 1. -1. -1.]
 [-1.  1.  1.]
 [-1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]
 [ 1.  1.  1.]
 [-1. -1. -1.]]
Actual Output: 
[[ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]]
Predicted Output: 
[[0.69034751]
 [0.6299119 ]
 [0.67661834]
 [0.61499755]
 [0.68425974]
 [0.62168242]
 [0.73276509]
 [0.56498433]]
Loss: 
1.4216653022333603


for iteration # 100

Input : 
[[ 1. -1.  1.]
 [ 1. -1. -1.]
 [-1.  1.  1.]
 [-1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]
 [ 1.  1.  1.]
 [-1. -1. -1.]]
Actual Output: 
[[ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]]
Predicted Output: 
[[2.15068662e-06]
 [9.33716485e-01]
 [2.14467680e-06]
 [9.33543088e-01]
 [9.72166734e-01]
 [8.64958608e-07]
 [5.14902233e-03]
 [5.80333761e-03]]
Loss: 
0.6289439181441375


for iteration # 200

Input : 
[[ 1. -1.  1.]
 [ 1. -1. -1.]
 [-1.  1.  1.]
 [-1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]
 [ 1.  1.  1.]
 [-1. -1. -1.]]
Actual Output: 
[[ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]


In [113]:
from sklearn.neural_network import MLPClassifier
X=np.array(([1,0,1],[1,0,0],[0,1,1],[0,1,0],[1,1,0],[0,0,1],[1,1,1],[0,0,0]), dtype=float)
y=np.array(([1],[1],[0],[1],[1],[0],[0],[0]), dtype=float)


In [117]:
clf = MLPClassifier(activation='identity',hidden_layer_sizes=(1), random_state=1)

In [118]:
clf.fit(X, y) 

C:\Anacoda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anacoda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='identity', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=1, learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=1, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [119]:
clf.coefs_

[array([[-0.38592986],
        [ 0.37654952],
        [-1.03099848]]), array([[-1.03588759]])]